#!/usr/bin/env bash
set -Eeuo pipefail

if [[ -z "${REPO_ROOT:-}" ]]; then
  REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi

export CORAMAIL_POSTGRES_DB="${CORAMAIL_POSTGRES_DB:-coramail}"
export CORAMAIL_POSTGRES_USER="${CORAMAIL_POSTGRES_USER:-coramail}"
export CORAMAIL_POSTGRES_PASSWORD="${CORAMAIL_POSTGRES_PASSWORD:-coramail}"
export CORAMAIL_POSTGRES_PORT="${CORAMAIL_POSTGRES_PORT:-5432}"
export CORAMAIL_DATABASE_URL="${CORAMAIL_DATABASE_URL:-postgresql://${CORAMAIL_POSTGRES_USER}:${CORAMAIL_POSTGRES_PASSWORD}@127.0.0.1:${CORAMAIL_POSTGRES_PORT}/${CORAMAIL_POSTGRES_DB}}"

export CORAMAIL_QDRANT_HTTP_PORT="${CORAMAIL_QDRANT_HTTP_PORT:-6333}"
export CORAMAIL_QDRANT_GRPC_PORT="${CORAMAIL_QDRANT_GRPC_PORT:-6334}"
export CORAMAIL_QDRANT_URL="${CORAMAIL_QDRANT_URL:-http://127.0.0.1:${CORAMAIL_QDRANT_HTTP_PORT}}"
export CORAMAIL_QDRANT_CASE_COLLECTION="${CORAMAIL_QDRANT_CASE_COLLECTION:-coramail_cases_clean_v2}"
export CORAMAIL_QDRANT_VECTOR_SIZE="${CORAMAIL_QDRANT_VECTOR_SIZE:-768}"

export CORAMAIL_DEMO_MODE="${CORAMAIL_DEMO_MODE:-false}"
export CORAMAIL_DEMO_SOURCE="${CORAMAIL_DEMO_SOURCE:-postgres}"
export CORAMAIL_LOCAL_DEV_DEFAULTS="${CORAMAIL_LOCAL_DEV_DEFAULTS:-true}"

export CORAMAIL_LLM_PROVIDER="${CORAMAIL_LLM_PROVIDER:-ollama}"
export CORAMAIL_LLM_BASE_URL="${CORAMAIL_LLM_BASE_URL:-http://127.0.0.1:11434/v1}"
export CORAMAIL_TEXT_MODEL="${CORAMAIL_TEXT_MODEL:-llama3.2:latest}"
export CORAMAIL_VISION_MODEL="${CORAMAIL_VISION_MODEL:-qwen2.5vl:7b}"
export CORAMAIL_EMBEDDING_MODEL="${CORAMAIL_EMBEDDING_MODEL:-nomic-embed-text:latest}"
export CORAMAIL_PADDLEOCR_ENABLED="${CORAMAIL_PADDLEOCR_ENABLED:-auto}"
export CORAMAIL_PADDLEOCR_MODE="${CORAMAIL_PADDLEOCR_MODE:-auto}"
export CORAMAIL_PADDLEOCR_DEVICE="${CORAMAIL_PADDLEOCR_DEVICE:-gpu}"
export CORAMAIL_PADDLEOCR_DOC_ORIENTATION="${CORAMAIL_PADDLEOCR_DOC_ORIENTATION:-false}"
export CORAMAIL_PADDLEOCR_DOC_UNWARPING="${CORAMAIL_PADDLEOCR_DOC_UNWARPING:-false}"
export CORAMAIL_PADDLEOCR_TEXTLINE_ORIENTATION="${CORAMAIL_PADDLEOCR_TEXTLINE_ORIENTATION:-false}"
export CORAMAIL_PADDLEOCR_TABLE_ORIENTATION="${CORAMAIL_PADDLEOCR_TABLE_ORIENTATION:-false}"
export CORAMAIL_PADDLEOCR_MKLDNN="${CORAMAIL_PADDLEOCR_MKLDNN:-false}"
export PADDLE_PDX_CACHE_HOME="${PADDLE_PDX_CACHE_HOME:-/tmp/coramail-paddlex-cache}"

export CORAMAIL_DEV_HOST="${CORAMAIL_DEV_HOST:-127.0.0.1}"
export CORAMAIL_DEV_PORT="${CORAMAIL_DEV_PORT:-8000}"
export CORAMAIL_DEV_RELOAD="${CORAMAIL_DEV_RELOAD:-true}"
export CORAMAIL_DEV_SEED_DEMO="${CORAMAIL_DEV_SEED_DEMO:-true}"
export CORAMAIL_DEV_RUN_APP="${CORAMAIL_DEV_RUN_APP:-false}"
